export const questions = {
    sde: {
        label: "Software Engineer",
        icon: "Code2",
        description: "DSA, system design, and OOP concepts",
        gradient: "from-purple-600 to-pink-500",
        hoverGlow: "hover:shadow-purple-500/20",
        list: [
            "Explain the difference between stack and queue.",
            "What is a REST API and how does it work?",
            "Explain OOPs concepts with a real-world example.",
            "How do you approach debugging a complex issue?",
            "What is the difference between a process and a thread?",
            "Explain the concept of Big O notation and why it matters.",
            "What is the difference between an abstract class and an interface?",
            "How do you handle a situation where you have to learn a new technology quickly?",
        ],
    },
    frontend: {
        label: "Frontend Developer",
        icon: "Monitor",
        description: "React, CSS, browser APIs, and UI patterns",
        gradient: "from-purple-500 to-pink-500",
        hoverGlow: "hover:shadow-pink-500/20",
        list: [
            "What is the virtual DOM in React?",
            "Explain CSS specificity.",
            "What are React hooks? Name 3 with use cases.",
            "How do you optimize a web application for performance?",
            "Explain the concept of closures in JavaScript.",
            "What is the difference between server-side rendering and client-side rendering?",
            "How do you handle state management in a large React application?",
            "Explain the event loop in JavaScript.",
        ],
    },
    dataAnalyst: {
        label: "Data Analyst",
        icon: "BarChart2",
        description: "ML, databases, statistics, and data wrangling",
        gradient: "from-purple-600 to-fuchsia-500",
        hoverGlow: "hover:shadow-purple-500/20",
        list: [
            "Explain the difference between supervised and unsupervised learning.",
            "What is normalization in databases?",
            "How would you handle missing data in a dataset?",
            "Explain the difference between correlation and causation.",
            "What is A/B testing and how do you determine if results are statistically significant?",
            "What is the difference between structured and unstructured data?",
            "Explain the concept of a 'pivot table' in data analysis.",
            "How do you tell a story with data to a non-technical stakeholder?",
        ],
    },
    backend: {
        label: "Backend Engineer",
        icon: "Server",
        description: "APIs, databases, microservices, and system design",
        gradient: "from-rose-500 to-red-600",
        hoverGlow: "hover:shadow-rose-500/20",
        list: [
            "Explain the CAP theorem.",
            "How do you handle database migrations with zero downtime?",
            "What is the difference between monolithic and microservices architectures?",
            "Explain how JWT authentication works.",
            "How do you prevent SQL injection attacks?",
            "What is horizontal vs vertical scaling?",
            "Explain the concept of a message queue and when to use it.",
            "How do you approach designing a system for high availability?",
        ],
    },
    pm: {
        label: "Product Manager",
        icon: "Target",
        description: "Roadmaps, agile, metrics, and stakeholder management",
        gradient: "from-amber-500 to-orange-600",
        hoverGlow: "hover:shadow-amber-500/20",
        list: [
            "How do you prioritize features for a product roadmap?",
            "Describe a time you had to say 'no' to a stakeholder.",
            "How do you measure the success of a new feature?",
            "Walk me through your process for conducting user research.",
            "How do you handle a situation where engineering says a feature will take twice as long as expected?",
            "What is a MVP and how do you decide what to include in it?",
            "How do you handle a product launch that didn't meet expectations?",
            "Explain the difference between 'Product Discovery' and 'Product Delivery'.",
        ],
    },
    devops: {
        label: "DevOps Engineer",
        icon: "GitBranch",
        description: "CI/CD, containers, cloud infrastructure, and monitoring",
        gradient: "from-purple-600 to-pink-600",
        hoverGlow: "hover:shadow-purple-500/20",
        list: [
            "What is the difference between Continuous Integration and Continuous Deployment?",
            "Explain Infrastructure as Code (IaC) and its benefits.",
            "How does Docker differ from a Virtual Machine?",
            "Describe a strategy for monitoring a production system.",
            "What is a blue-green deployment?",
            "What is the role of Kubernetes in a DevOps pipeline?",
            "How do you manage secrets and sensitive configuration in a CI/CD environment?",
            "Explain the concept of 'Shift Left' in the context of DevOps and security.",
        ],
    },
    python: {
        label: "Python Developer",
        icon: "Terminal",
        description: "Core Python, Django, memory management, and generators",
        gradient: "from-yellow-500 to-pink-500",
        hoverGlow: "hover:shadow-pink-500/20",
        list: [
            "What is the difference between a list and a tuple in Python?",
            "Explain decorators in Python with an example.",
            "What is a generator and how is it different from a normal function?",
            "What are *args and **kwargs in Python?",
            "How does Python manage memory?",
            "Explain list comprehension with an example.",
            "What is the GIL (Global Interpreter Lock)?",
        ],
    },
    aiml: {
        label: "AI / ML Engineer",
        icon: "Brain",
        description: "Neural networks, RAG, embeddings, and optimization",
        gradient: "from-purple-500 to-pink-600",
        hoverGlow: "hover:shadow-purple-500/20",
        list: [
            "What is the difference between overfitting and underfitting?",
            "Explain how a neural network works in simple terms.",
            "What is gradient descent?",
            "What is the difference between classification and regression?",
            "Explain what a transformer model is.",
            "What is the difference between precision and recall?",
            "What is a vector embedding?",
            "How does RAG (Retrieval Augmented Generation) work?",
        ],
    },
    fullstack: {
        label: "Full Stack Developer",
        icon: "Layers",
        description: "Frontend, backend, databases, and APIs",
        gradient: "from-fuchsia-500 to-rose-600",
        hoverGlow: "hover:shadow-fuchsia-500/20",
        list: [
            "Explain the difference between client-side and server-side rendering.",
            "What is JWT and how does authentication work with it?",
            "What is the difference between SQL and NoSQL databases?",
            "Explain the MVC architecture pattern.",
            "What is CORS and why does it happen?",
            "How does a cookie differ from localStorage?",
            "What is middleware in Express.js?",
        ],
    },
    cybersecurity: {
        label: "Cybersecurity",
        icon: "Shield",
        description: "Network security, encryption, and vulnerability prevention",
        gradient: "from-red-600 to-red-800",
        hoverGlow: "hover:shadow-red-600/20",
        list: [
            "What is the difference between symmetric and asymmetric encryption?",
            "Explain what SQL injection is and how to prevent it.",
            "What is a man-in-the-middle attack?",
            "What is XSS (Cross-Site Scripting)?",
            "Explain what HTTPS does differently from HTTP.",
            "What is a firewall and how does it work?",
            "What is two-factor authentication and why is it important?",
        ],
    },
    flutter: {
        label: "Flutter / Mobile Dev",
        icon: "Smartphone",
        description: "Dart, widgets, state management, and mobile UX",
        gradient: "from-blue-400 to-cyan-500",
        hoverGlow: "hover:shadow-blue-400/20",
        list: [
            "What is the difference between StatefulWidget and StatelessWidget?",
            "Explain the widget tree in Flutter.",
            "What is the difference between hot reload and hot restart?",
            "How does state management work in Flutter? Name 2 approaches.",
            "Explain what a Future and async/await does in Dart.",
            "What is the pubspec.yaml file used for?",
            "How do you optimize a Flutter app for performance?",
            "What is the purpose of 'Keys' in Flutter?",
        ],
    },
    database: {
        label: "Database Admin (SQL)",
        icon: "Database",
        description: "SQL, optimization, architecture, and normalization",
        gradient: "from-orange-500 to-red-500",
        hoverGlow: "hover:shadow-orange-500/20",
        list: [
            "What is the difference between PRIMARY KEY and UNIQUE KEY?",
            "Explain ACID properties in databases.",
            "What is indexing and why is it used?",
            "What is the difference between INNER JOIN and LEFT JOIN?",
            "What is a stored procedure?",
            "Explain normalization — 1NF, 2NF, 3NF.",
            "What is a deadlock in databases and how do you prevent it?",
        ],
    },
    uiux: {
        label: "UI/UX Designer",
        icon: "Pen",
        description: "Wireframes, user research, accessibility, and design systems",
        gradient: "from-pink-400 to-orange-400",
        hoverGlow: "hover:shadow-pink-400/20",
        list: [
            "What is the difference between UI and UX?",
            "Explain what a design system is.",
            "What is the difference between wireframe, mockup, and prototype?",
            "What is user research and why is it important?",
            "Explain the concept of visual hierarchy.",
            "What is accessibility in design and why does it matter?",
            "How do you handle negative feedback on your designs?",
            "What is the importance of micro-interactions in UI design?",
        ],
    },
    businessAnalyst: {
        label: "Business Analyst",
        icon: "TrendingUp",
        description: "Requirements, processes, and business strategy",
        gradient: "from-blue-600 to-indigo-700",
        hoverGlow: "hover:shadow-blue-600/20",
        list: [
            "What is the role of a Business Analyst in a project?",
            "How do you gather requirements from stakeholders?",
            "Explain the difference between functional and non-functional requirements.",
            "What is a BRD (Business Requirements Document)?",
            "How do you handle scope creep during a project?",
            "Explain the concept of SWOT analysis.",
            "What is gap analysis and when do you use it?",
            "How do you translate business needs into technical specifications?",
        ],
    },
    marketingAnalyst: {
        label: "Marketing Analyst",
        icon: "Megaphone",
        description: "Campaigns, ROI, customer behavior, and SEO",
        gradient: "from-orange-500 to-red-600",
        hoverGlow: "hover:shadow-orange-500/20",
        list: [
            "How do you measure the ROI of a marketing campaign?",
            "What is the difference between SEO and SEM?",
            "Explain the marketing funnel and key metrics at each stage.",
            "How do you analyze customer churn and its causes?",
            "What tools do you use for web analytics?",
            "How would you optimize an underperforming marketing channel?",
            "What is customer segmentation and why is it important?",
            "How do you interpret data from social media campaigns?",
        ],
    },
    financialAnalyst: {
        label: "Financial Analyst",
        icon: "DollarSign",
        description: "Budgeting, forecasting, and financial modeling",
        gradient: "from-emerald-600 to-green-700",
        hoverGlow: "hover:shadow-emerald-600/20",
        list: [
            "What are the three main financial statements?",
            "Explain the difference between cash and accrual accounting.",
            "What is NPV and IRR and how are they used in decision making?",
            "How do you perform a variance analysis?",
            "What is working capital and why is it important?",
            "How do you model a company's future revenue?",
            "What is the difference between operating and capital leases?",
            "Explain the concept of 'Time Value of Money'.",
        ],
    },
    hrExecutive: {
        label: "HR Executive",
        icon: "Users",
        description: "Recruitment, payroll, and employee relations",
        gradient: "from-indigo-500 to-purple-600",
        hoverGlow: "hover:shadow-indigo-500/20",
        list: [
            "How do you source candidates for niche roles?",
            "Explain the end-to-end recruitment process.",
            "How do you handle a conflict between two employees?",
            "What are the key components of an employee benefits package?",
            "How do you measure employee engagement?",
            "Explain the process of performance appraisal.",
            "How do you handle a situation where a top-performing employee resigns?",
            "What is the importance of diversity and inclusion in the workplace?",
        ],
    },
    opsManager: {
        label: "Operations Manager",
        icon: "Settings",
        description: "Efficiency, logistics, and process improvement",
        gradient: "from-zinc-600 to-zinc-800",
        hoverGlow: "hover:shadow-zinc-600/20",
        list: [
            "How do you optimize a supply chain for cost and speed?",
            "Explain the concept of Lean manufacturing or Six Sigma.",
            "How do you manage vendor relationships and contracts?",
            "Describe a time you improved a business process.",
            "How do you handle a major operational bottleneck?",
            "What metrics do you use to measure operational efficiency?",
            "How do you approach risk management in operations?",
            "What is your strategy for resource allocation during peak demand?",
        ],
    },
    supplyChainAnalyst: {
        label: "Supply Chain Analyst",
        icon: "Truck",
        description: "Inventory, procurement, and distribution",
        gradient: "from-amber-600 to-orange-700",
        hoverGlow: "hover:shadow-amber-600/20",
        list: [
            "What is the difference between procurement and purchasing?",
            "Explain the concept of safety stock and how to calculate it.",
            "How do you manage inventory turnover ratio?",
            "What is a bullwhip effect in supply chain and how to mitigate it?",
            "How do you evaluate and select a new supplier?",
            "What tools do you use for demand forecasting?",
            "Explain the concept of 'Just-in-Time' (JIT) inventory.",
            "How do you handle a major supply chain disruption?",
        ],
    },
    contentStrategist: {
        label: "Content Strategist",
        icon: "Edit3",
        description: "Content lifecycle, SEO, and brand voice",
        gradient: "from-pink-500 to-rose-600",
        hoverGlow: "hover:shadow-pink-500/20",
        list: [
            "How do you define a brand's tone of voice?",
            "Explain the content lifecycle from ideation to archiving.",
            "How do you align content strategy with business goals?",
            "What is a content audit and how do you conduct one?",
            "How do you measure the effectiveness of content?",
            "How do you optimize content for different social media platforms?",
            "What is a 'pillar page' and 'cluster content' strategy?",
            "How do you approach content personalization for different user segments?",
        ],
    },
    salesEngineer: {
        label: "Sales Engineer",
        icon: "Briefcase",
        description: "Demos, technical sales, and solutions",
        gradient: "from-blue-500 to-cyan-600",
        hoverGlow: "hover:shadow-blue-500/20",
        list: [
            "How do you handle a technical objection from a potential client?",
            "Describe your process for conducting a product demo.",
            "How do you bridge the gap between sales and engineering teams?",
            "Explain a complex technical product to a non-technical stakeholder.",
            "How do you qualify a lead from a technical perspective?",
            "What is a PoC (Proof of Concept) and how do you manage one?",
            "How do you handle a request for a feature that is not currently on the roadmap?",
            "What is the importance of post-sales technical support in relationship building?",
        ],
    },
    cloudEngineer: {
        label: "Cloud Engineer",
        icon: "Cloud",
        description: "AWS, Azure, serverless, and cloud architecture",
        gradient: "from-sky-400 to-blue-500",
        hoverGlow: "hover:shadow-sky-400/20",
        list: [
            "What is the difference between IaaS, PaaS, and SaaS?",
            "Explain the concept of serverless computing.",
            "How do you ensure high availability in a cloud environment?",
            "What is a VPC and how do you secure it?",
            "Explain the shared responsibility model in cloud computing.",
            "How do you optimize cloud costs for a large-scale application?",
            "What is auto-scaling and how do you configure it?",
            "How do you handle data migration to the cloud?",
        ],
    },
    qaEngineer: {
        label: "QA Engineer",
        icon: "CheckCircle",
        description: "Automation, manual testing, and bug reporting",
        gradient: "from-emerald-500 to-green-600",
        hoverGlow: "hover:shadow-emerald-500/20",
        list: [
            "What is the difference between smoke testing and regression testing?",
            "Explain the bug lifecycle from discovery to closure.",
            "How do you decide which tests to automate?",
            "What is the difference between black-box and white-box testing?",
            "Describe your process for writing a test plan.",
            "How do you handle a bug that you cannot reproduce?",
            "Explain the concept of 'test-driven development' (TDD).",
            "What is the role of performance testing in QA?",
        ],
    },
    embeddedEngineer: {
        label: "Embedded Systems",
        icon: "Cpu",
        description: "Microcontrollers, RTOS, and firmware",
        gradient: "from-slate-600 to-slate-800",
        hoverGlow: "hover:shadow-slate-600/20",
        list: [
            "What is the difference between a microcontroller and a microprocessor?",
            "Explain what an RTOS (Real-Time Operating System) is.",
            "How do you minimize power consumption in an embedded system?",
            "What is an interrupt and how do you handle it in code?",
            "Explain the difference between I2C and SPI communication protocols.",
            "How do you debug an embedded system with limited resources?",
            "What is a watchdog timer and why is it used?",
            "Explain the concept of DMA (Direct Memory Access).",
        ],
    },
    blockchainDev: {
        label: "Blockchain Dev",
        icon: "Link",
        description: "Smart contracts, Web3, and consensus",
        gradient: "from-violet-700 to-purple-800",
        hoverGlow: "hover:shadow-violet-700/20",
        list: [
            "Explain how a blockchain consensus mechanism works.",
            "What is a smart contract and how do you secure it?",
            "What is the difference between Proof of Work and Proof of Stake?",
            "How do you handle gas optimization in Ethereum?",
            "What is a decentralized application (dApp)?",
            "Explain the concept of a private vs. public blockchain.",
            "What is a bridge in the context of cross-chain communication?",
            "How does a 51% attack work and how can it be prevented?",
        ],
    },
    arvrDev: {
        label: "AR/VR Developer",
        icon: "Glasses",
        description: "Unity, 3D engines, and spatial computing",
        gradient: "from-fuchsia-600 to-purple-700",
        hoverGlow: "hover:shadow-fuchsia-600/20",
        list: [
            "What is the difference between Augmented Reality and Virtual Reality?",
            "Explain how spatial mapping works in AR.",
            "How do you optimize 3D assets for mobile VR performance?",
            "What is a shader and how do you use it in Unity or Unreal?",
            "Explain the concept of 6DoF (Six Degrees of Freedom).",
            "How do you handle user locomotion in a VR environment to avoid motion sickness?",
            "What is occlusion in AR and why is it difficult to implement?",
            "How do you handle multi-user interaction in a shared AR space?",
        ],
    },
    gameDev: {
        label: "Game Developer",
        icon: "Gamepad2",
        description: "Physics, game loops, and graphics",
        gradient: "from-red-500 to-orange-600",
        hoverGlow: "hover:shadow-red-500/20",
        list: [
            "Explain the game loop and its importance.",
            "What is a physics engine and how does it handle collisions?",
            "How do you optimize draw calls in a 3D game?",
            "Explain the difference between forward and deferred rendering.",
            "What is a state machine and how is it used in game AI?",
            "How do you handle multiplayer synchronization and latency?",
            "What is procedural generation and when is it useful?",
            "How do you approach game balancing based on player feedback?",
        ],
    },
    techWriter: {
        label: "Technical Writer",
        icon: "FileText",
        description: "Documentation, API guides, and user manuals",
        gradient: "from-teal-500 to-cyan-600",
        hoverGlow: "hover:shadow-teal-500/20",
        list: [
            "How do you explain a complex technical feature to a non-technical user?",
            "What is your process for creating an API documentation guide?",
            "How do you ensure documentation stays up-to-date with code changes?",
            "What tools do you use for technical writing (e.g., Markdown, DITA)?",
            "How do you gather information from busy subject matter experts?",
            "Describe your approach to organizing a large knowledge base.",
            "What is the importance of 'user personas' in technical writing?",
            "How do you measure the helpfulness of your documentation?",
        ],
    },
    scrumMaster: {
        label: "Scrum Master",
        icon: "RefreshCw",
        description: "Agile, sprints, and team facilitation",
        gradient: "from-indigo-600 to-blue-700",
        hoverGlow: "hover:shadow-indigo-600/20",
        list: [
            "What are the core values and principles of Agile?",
            "Explain the different ceremonies in Scrum.",
            "How do you handle a team member who is not following Scrum practices?",
            "What is a sprint backlog and how is it different from a product backlog?",
            "How do you measure a team's velocity and what does it tell you?",
            "How do you facilitate a retrospective to ensure it's productive?",
            "What do you do when a team consistently fails to meet its sprint goal?",
            "How do you protect the team from outside interruptions during a sprint?",
        ],
    },
};

export const companyQuestions: Record<string, { label: string; icon: string; domain: string; color: string; list: string[] }> = {
    tcs: {
        label: "TCS",
        icon: "🔵",
        domain: "tcs.com",
        color: "#0033A0",
        list: [
            "Tell me about yourself.",
            "What is the difference between abstract class and interface in Java?",
            "Explain the concept of polymorphism with an example.",
            "What is a linked list? Explain types.",
            "What is normalization? Explain 1NF, 2NF, 3NF.",
            "Write a program to reverse a string without using built-in functions.",
            "What is SDLC? Explain each phase.",
            "What are your strengths and weaknesses?",
            "Where do you see yourself in 5 years?",
            "Why do you want to join TCS?",
        ],
    },
    infosys: {
        label: "Infosys",
        icon: "🟢",
        domain: "infosys.com",
        color: "#007CC3",
        list: [
            "Explain the difference between stack and heap memory.",
            "What is a deadlock? How do you prevent it?",
            "What is the difference between GET and POST in HTTP?",
            "Explain OOPS concepts — encapsulation, abstraction, inheritance, polymorphism.",
            "What is the difference between Array and ArrayList in Java?",
            "What is a foreign key in SQL?",
            "Explain what cloud computing is in simple terms.",
            "What is Agile methodology?",
            "Describe a project you've worked on and your role in it.",
            "Why Infosys over other companies?",
        ],
    },
    wipro: {
        label: "Wipro",
        icon: "🟡",
        domain: "wipro.com",
        color: "#341C75",
        list: [
            "What is the difference between compiler and interpreter?",
            "Explain recursion with an example.",
            "What is a binary search tree?",
            "What is the difference between TCP and UDP?",
            "Explain what an API is to a non-technical person.",
            "What is the difference between == and === in JavaScript?",
            "What is a join in SQL? Name the types.",
            "What is version control and why is it important?",
            "Tell me about a time you solved a difficult problem.",
            "Why do you want to work at Wipro?",
        ],
    },
    cognizant: {
        label: "Cognizant",
        icon: "🔷",
        domain: "cognizant.com",
        color: "#1473C8",
        list: [
            "What is the difference between overloading and overriding?",
            "Explain the MVC design pattern.",
            "What is a primary key? Can it be null?",
            "What is the difference between synchronous and asynchronous programming?",
            "Explain what an index is in a database and when to use it.",
            "What is the difference between HTML, CSS, and JavaScript?",
            "What are design patterns? Name 2 with examples.",
            "How do you handle pressure and tight deadlines?",
            "Describe your final year project.",
            "Why Cognizant?",
        ],
    },
    accenture: {
        label: "Accenture",
        icon: "🟣",
        domain: "accenture.com",
        color: "#A100FF",
        list: [
            "What is the difference between a class and an object?",
            "Explain what REST and SOAP are.",
            "What is multithreading? How is it different from multiprocessing?",
            "What is the difference between WHERE and HAVING in SQL?",
            "Explain what DevOps is in simple terms.",
            "What is a microservice architecture?",
            "What is the difference between unit testing and integration testing?",
            "Tell me about a time you worked in a team and faced a conflict.",
            "What are your career goals?",
            "Why do you want to join Accenture?",
        ],
    },
    hcl: {
        label: "HCL Technologies",
        icon: "🔴",
        domain: "hcltech.com",
        color: "#0057A8",
        list: [
            "What is the difference between procedural and object-oriented programming?",
            "Explain what an operating system does.",
            "What is virtual memory?",
            "What is the difference between DML and DDL in SQL?",
            "Explain what a RESTful API is.",
            "What is the difference between black box and white box testing?",
            "What is Agile vs Waterfall?",
            "Describe a challenging academic project you completed.",
            "What motivates you as a developer?",
            "Why HCL?",
        ],
    },
    zoho: {
        label: "Zoho",
        icon: "🟠",
        domain: "zoho.com",
        color: "#E42527",
        list: [
            "Write a program to find the factorial of a number.",
            "Explain the difference between BFS and DFS.",
            "What is a hash table and how does it handle collisions?",
            "What is the time complexity of binary search?",
            "Explain what a closure is in JavaScript.",
            "What is the difference between shallow copy and deep copy?",
            "Design a simple URL shortener — what data structure would you use?",
            "Write a SQL query to find the second highest salary.",
            "What is your approach when you get stuck on a problem?",
            "Why do you want to join Zoho?",
        ],
    },
    amazon: {
        label: "Amazon",
        icon: "📦",
        domain: "amazon.com",
        color: "#FF9900",
        list: [
            "Tell me about a time you dealt with ambiguity and had to make a decision without complete information.",
            "What is the difference between a stack and a heap?",
            "Explain what a binary tree is and write code to traverse it.",
            "What is the difference between HashMap and HashTable in Java?",
            "Design a parking lot system — what classes and methods would you create?",
            "What is eventual consistency in distributed systems?",
            "Tell me about a time you failed and what you learned from it.",
            "How would you design a notification system that handles millions of users?",
            "What is the difference between SQL and NoSQL? When would you pick one over the other?",
            "Why Amazon? Which Leadership Principle resonates with you the most?",
        ],
    },
    google: {
        label: "Google",
        icon: "🔍",
        domain: "google.com",
        color: "#4285F4",
        list: [
            "Given an array of integers, find two numbers that add up to a target sum.",
            "Explain how a hash map works internally.",
            "What is the time and space complexity of merge sort?",
            "How would you design Google Search at a high level?",
            "Explain the concept of dynamic programming with an example.",
            "What is a graph? Explain BFS vs DFS with use cases.",
            "How would you detect a cycle in a linked list?",
            "What happens when you type a URL in the browser and press Enter?",
            "Tell me about a project where you had to learn something new quickly.",
            "What makes you a good fit for Google's culture?",
        ],
    },
    microsoft: {
        label: "Microsoft",
        icon: "🪟",
        domain: "microsoft.com",
        color: "#00A4EF",
        list: [
            "Explain the difference between process and thread with a real example.",
            "What is a virtual function in C++? How is it different from a pure virtual function?",
            "How would you implement a LRU cache?",
            "Explain the SOLID principles of software design.",
            "What is dependency injection and why is it useful?",
            "How does garbage collection work in Java or C#?",
            "Design a simple chat application — what components would you need?",
            "What is the difference between optimistic and pessimistic locking?",
            "Tell me about a time you disagreed with a teammate and how you resolved it.",
            "Why Microsoft? What product of ours do you use daily and how would you improve it?",
        ],
    },
    swiggy: {
        label: "Swiggy",
        icon: "🍔",
        domain: "swiggy.com",
        color: "#FC8019",
        list: [
            "How would you design the backend for a food delivery app like Swiggy?",
            "What is rate limiting and why is it important for an API?",
            "Explain how you would handle real-time order tracking.",
            "What is the difference between WebSockets and HTTP polling?",
            "How would you design a recommendation system for food items?",
            "What is a message queue? Name one tool and explain its use.",
            "How do you ensure high availability for a system that cannot go down?",
            "Write a SQL query to find the most ordered item in the last 30 days.",
            "How would you handle a sudden traffic spike during a sale event?",
            "Why do you want to work at a startup like Swiggy over a large MNC?",
        ],
    },
    zomato: {
        label: "Zomato",
        icon: "🍕",
        domain: "zomato.com",
        color: "#E23744",
        list: [
            "How would you design the restaurant search feature with filters?",
            "What is geohashing and how would you use it for nearby restaurant search?",
            "Explain caching strategies — when would you use Redis?",
            "How would you handle payment failures in an order flow?",
            "What is the difference between synchronous and event-driven architecture?",
            "How would you design a review and rating system that prevents spam?",
            "What is horizontal scaling? How is it different from vertical scaling?",
            "Write a query to find restaurants with average rating above 4 and more than 100 reviews.",
            "Tell me about a time you built something under a tight deadline.",
            "Why Zomato? What would you improve in our app?",
        ],
    },
    startupGeneral: {
        label: "Startup (General)",
        icon: "🚀",
        domain: "startupgeneral.com",
        color: "#6C63FF",
        list: [
            "Tell me about a side project or personal project you built from scratch.",
            "How do you stay updated with new technologies?",
            "What is an MVP and how would you decide what goes in it?",
            "How comfortable are you switching between frontend and backend tasks?",
            "Tell me about a time you had to figure something out with no guidance.",
            "What is technical debt and how do you manage it?",
            "How do you approach learning a new framework or tool quickly?",
            "What open source projects have you contributed to or explored?",
            "How do you handle feedback on your code during a code review?",
            "What excites you about working at an early-stage startup?",
        ],
    },
    phonepe: {
        label: "PhonePe",
        icon: "📱",
        domain: "phonepe.com",
        color: "#6739B7",
        list: [
            "How do you ensure 99.99% uptime for a payment gateway?",
            "Explain the transactional lifecycle of a UPI payment.",
            "How would you handle a distributed transaction across multiple microservices?",
            "What is the importance of idempotency in payment APIs?",
            "Design a digital wallet system — how do you prevent double-spending?",
            "How do you handle high-concurrency database updates during a flash sale?",
            "Why do you want to work in the Fintech space at PhonePe?",
        ],
    },
    paytm: {
        label: "Paytm",
        icon: "💸",
        domain: "paytm.com",
        color: "#00B9F1",
        list: [
            "How do you scale a system to handle 100 million daily active users?",
            "Explain the difference between a mobile wallet and a bank account from a technical perspective.",
            "How do you handle security and fraud detection in real-time transactions?",
            "What is a KYC process and how would you automate it using AI?",
            "How do you manage data consistency in a highly distributed system?",
            "Describe a time you optimized a slow API or database query.",
            "What is your favorite Paytm feature and how would you improve it?",
        ],
    },
    cred: {
        label: "CRED",
        icon: "💎",
        domain: "cred.club",
        color: "#000000",
        list: [
            "How would you design the 'CRED coins' reward system for scalability?",
            "What is your approach to building a premium, high-performance UI/UX?",
            "How do you handle sensitive user financial data securely?",
            "Explain the importance of event-driven architecture for real-time notifications.",
            "How do you maintain a high bar for code quality and design consistency?",
            "What is your opinion on CRED's unique design language?",
            "How would you design a system to track credit card statements for millions of users?",
        ],
    },
    razorpay: {
        label: "Razorpay",
        icon: "💳",
        domain: "razorpay.com",
        color: "#0055D4",
        list: [
            "How would you design a checkout system that supports multiple payment methods?",
            "What is a webhook and why is it critical for payment providers?",
            "Explain the difference between a payment gateway and a payment aggregator.",
            "How do you handle complex refund logic across different banks?",
            "Design a subscription billing system with support for trials and discounts.",
            "How do you ensure low latency for payment authorization calls?",
            "Why are you interested in building infrastructure for the Indian internet economy?",
        ],
    },
    flipkart: {
        label: "Flipkart",
        icon: "🛒",
        domain: "flipkart.com",
        color: "#2874F0",
        list: [
            "How would you design the search and filtering system for millions of products?",
            "Explain how you would handle inventory synchronization across multiple warehouses.",
            "How do you design a robust recommendation engine for 'frequently bought together' items?",
            "Describe a strategy for handling extreme traffic spikes during Big Billion Days.",
            "How do you optimize the delivery route for a last-mile logistics system?",
            "What is the difference between a marketplace model and an inventory-led model?",
            "Why Flipkart, and how would you contribute to its supply chain innovation?",
        ],
    },
    myntra: {
        label: "Myntra",
        icon: "👗",
        domain: "myntra.com",
        color: "#FF3F6C",
        list: [
            "How would you design a personalized fashion feed for each user?",
            "What is your approach to building a high-fidelity image rendering system for apparel?",
            "How do you handle real-time inventory updates for limited-edition sales?",
            "Explain how you would implement a 'virtual try-on' feature using AR.",
            "How do you optimize mobile app performance for users on slow networks?",
            "What metrics would you track to measure the success of a new fashion category?",
            "Why Myntra, and what is your take on fashion-tech trends?",
        ],
    },
    meesho: {
        label: "Meesho",
        icon: "🛍️",
        domain: "meesho.com",
        color: "#F43397",
        list: [
            "How would you design a platform that supports millions of small-scale resellers?",
            "Explain how you would implement a multi-level referral and commission system.",
            "How do you handle data localization and support for regional languages?",
            "What is your strategy for optimizing shipping costs for low-ASP products?",
            "How do you build trust in a social commerce environment?",
            "How would you design a community feature for resellers to share tips and tricks?",
            "Why Meesho, and how do you relate to its mission of democratizing e-commerce?",
        ],
    },
    byjus: {
        label: "Byju's",
        icon: "📚",
        domain: "byjus.com",
        color: "#802282",
        list: [
            "How would you design a low-latency video streaming platform for online classes?",
            "Explain how you would implement an adaptive learning path for students.",
            "How do you handle real-time student-teacher interaction in a live class?",
            "What is your approach to gamifying the learning experience for kids?",
            "How do you scale your infrastructure to handle millions of concurrent learners?",
            "Design a progress tracking dashboard for parents and teachers.",
            "Why Edtech, and what is your vision for the future of online education?",
        ],
    },
    unacademy: {
        label: "Unacademy",
        icon: "🎓",
        domain: "unacademy.com",
        color: "#2D81F7",
        list: [
            "How would you design a leaderboard system for competitive exam preparation?",
            "Explain how you would implement a real-time doubt-clearing feature.",
            "How do you optimize content delivery for students in remote areas?",
            "What is your strategy for managing a large library of recorded video content?",
            "How do you design a subscription model with varying access levels?",
            "How would you implement a recommendation engine for exam-specific courses?",
            "Why Unacademy, and how would you help democratize high-quality coaching?",
        ],
    },
    scaler: {
        label: "Scaler",
        icon: "🚀",
        domain: "scaler.com",
        color: "#000000",
        list: [
            "How would you design a mentorship platform that matches students with industry experts?",
            "Explain how you would implement an automated coding assessment tool.",
            "How do you build a community platform for alumni and current students?",
            "What is your approach to designing a curriculum that stays relevant to industry trends?",
            "How do you measure the effectiveness of a long-term upskilling program?",
            "How would you design a system to track student placement progress?",
            "Why Scaler, and how do you stay updated with the tech industry yourself?",
        ],
    },
    ola: {
        label: "Ola",
        icon: "🚕",
        domain: "olacabs.com",
        color: "#A2C61E",
        list: [
            "How would you design a real-time cab-matching algorithm?",
            "Explain how you would handle surge pricing logic during peak hours.",
            "How do you ensure accurate GPS tracking and distance calculation?",
            "Design a payment system that handles driver payouts and customer refunds.",
            "How do you manage a large fleet of vehicles in real-time?",
            "What is your approach to building a robust SOS/Safety feature in the app?",
            "Why Ola, and what are your thoughts on the transition to electric mobility?",
        ],
    },
    rapido: {
        label: "Rapido",
        icon: "🛵",
        domain: "rapido.in",
        color: "#F9D915",
        list: [
            "How would you design a matching algorithm specifically for bike taxis?",
            "Explain how you would optimize routes for faster urban commuting.",
            "How do you handle safety and insurance integration for bike rides?",
            "What is your strategy for expanding into the logistics and delivery space?",
            "How do you handle extreme traffic conditions in your time-to-arrival estimates?",
            "How would you design a system for driver onboarding and documentation?",
            "Why Rapido, and what is the potential of bike-taxis in India?",
        ],
    },
    nammaYatri: {
        label: "Namma Yatri",
        icon: "🛺",
        domain: "nammayatri.in",
        color: "#FBD106",
        list: [
            "How would you design a decentralized or zero-commission ride-hailing app?",
            "Explain the importance of open-source and community-driven development in mobility.",
            "How do you handle real-time driver availability without a centralized commission model?",
            "What is your approach to building a simple, high-performance app for auto drivers?",
            "How do you ensure data privacy and security in a public-good tech platform?",
            "How would you implement a fair rating system for both drivers and riders?",
            "Why Namma Yatri, and what are your thoughts on the ONDC ecosystem?",
        ],
    },
    ibm: {
        label: "IBM",
        icon: "🏢",
        domain: "ibm.com",
        color: "#006699",
        list: [
            "What is your experience with hybrid cloud and enterprise-level infrastructure?",
            "Explain the importance of AI ethics and bias mitigation in software development.",
            "How do you approach a complex problem using IBM's Design Thinking framework?",
            "What is your understanding of mainframe systems and their modern relevance?",
            "How do you manage large-scale legacy system migrations?",
            "Describe a time you contributed to an open-source project or research paper.",
            "Why IBM, and how do you see yourself contributing to its legacy of innovation?",
        ],
    },
    capgemini: {
        label: "Capgemini",
        icon: "🔷",
        domain: "capgemini.com",
        color: "#0070AD",
        list: [
            "How do you handle client requirements that are constantly changing?",
            "Explain your approach to digital transformation for a large enterprise.",
            "How do you ensure code quality and standards across global teams?",
            "What is your experience with SAP or other enterprise resource planning tools?",
            "Describe a time you had to learn a new domain quickly for a project.",
            "How do you stay updated with emerging technologies like 5G or Edge computing?",
            "Why Capgemini, and what values do you bring to a global consulting firm?",
        ],
    },
    mphasis: {
        label: "Mphasis",
        icon: "💠",
        domain: "mphasis.com",
        color: "#000000",
        list: [
            "How would you approach modernizing a legacy banking system?",
            "Explain your experience with cloud-native application development.",
            "How do you ensure security and compliance in financial service applications?",
            "What is your strategy for optimizing application performance for high-volume transactions?",
            "Describe a time you solved a complex technical debt issue.",
            "How do you manage stakeholder expectations in an agile-outsourced model?",
            "Why Mphasis, and what is your take on the future of specialized IT services?",
        ],
    },
    ltimindtree: {
        label: "LTIMindtree",
        icon: "📐",
        domain: "ltimindtree.com",
        color: "#000000",
        list: [
            "How do you approach end-to-end digital engineering for a Fortune 500 client?",
            "Explain your experience with data engineering and analytics at scale.",
            "How do you ensure seamless integration between diverse technology stacks?",
            "Describe a time you led a team through a major technology transition.",
            "What is your approach to building resilient and scalable cloud architectures?",
            "How do you balance innovation with the stability needs of an enterprise client?",
            "Why LTIMindtree, and what excites you about the merged entity's capabilities?",
        ],
    },
    freshworks: {
        label: "Freshworks",
        icon: "🍃",
        domain: "freshworks.com",
        color: "#00A3FF",
        list: [
            "How would you design a multi-tenant SaaS architecture?",
            "Explain how you would implement a real-time omnichannel messaging system.",
            "How do you handle data isolation and security in a shared database environment?",
            "What is your approach to building a highly customizable CRM dashboard?",
            "How do you optimize API performance for third-party integrations?",
            "How do you balance adding new features with maintaining a simple UI/UX?",
            "Why Freshworks, and what is your experience with customer-centric product development?",
        ],
    },
    chargebee: {
        label: "Chargebee",
        icon: "🐝",
        domain: "chargebee.com",
        color: "#FF9900",
        list: [
            "How would you design a global subscription billing engine with tax compliance?",
            "Explain how you would handle complex prorated billing logic.",
            "How do you ensure high reliability for recurring payment processing?",
            "What is your approach to building an extensible plugin architecture for SaaS?",
            "How do you handle a large volume of concurrent dunning and notification events?",
            "How would you design a revenue recognition and reporting system?",
            "Why Chargebee, and what is your understanding of the subscription economy?",
        ],
    },
    kissflow: {
        label: "Kissflow",
        icon: "💋",
        domain: "kissflow.com",
        color: "#E23744",
        list: [
            "How would you design a no-code/low-code workflow automation engine?",
            "Explain how you would implement a visual drag-and-drop form builder.",
            "How do you handle dynamic schema generation for user-defined data structures?",
            "What is your strategy for optimizing complex workflow execution paths?",
            "How do you balance flexibility with ease of use in a BPM platform?",
            "How would you design a system for real-time collaboration on process models?",
            "Why Kissflow, and what are your thoughts on the 'democratization of IT'?",
        ],
    },
    isro: {
        label: "ISRO",
        icon: "🚀",
        domain: "isro.gov.in",
        color: "#FF9900",
        list: [
            "What is the importance of real-time embedded systems in satellite control?",
            "How do you ensure software reliability for mission-critical space missions?",
            "Explain the challenges of data transmission and telemetry in deep space.",
            "How do you handle radiation-hardened hardware in your software design?",
            "Describe a time you worked on a high-precision engineering problem.",
            "What is your understanding of orbital mechanics and its computational needs?",
            "Why do you want to contribute to India's space program at ISRO?",
        ],
    },
    drdo: {
        label: "DRDO",
        icon: "🛡️",
        domain: "drdo.gov.in",
        color: "#003366",
        list: [
            "How do you ensure cybersecurity in high-stakes defense communication networks?",
            "Explain the importance of indigenous technology development for national security.",
            "How do you approach building robust software for radar or missile guidance systems?",
            "What is your experience with high-performance computing and simulation?",
            "Describe a time you handled highly sensitive or confidential information.",
            "How do you handle the trade-offs between performance and security in defense tech?",
            "Why DRDO, and what motivates you to work for national defense?",
        ],
    },
    hal: {
        label: "HAL",
        icon: "✈️",
        domain: "hal-india.co.in",
        color: "#004B87",
        list: [
            "What is the role of avionics software in modern fighter aircraft?",
            "How do you ensure DO-178C compliance in aerospace software development?",
            "Explain the challenges of real-time flight control system implementation.",
            "How do you approach hardware-in-the-loop (HIL) testing for aircraft systems?",
            "Describe your experience with embedded C/C++ and low-level programming.",
            "How do you manage the lifecycle of long-term aerospace projects?",
            "Why HAL, and what is your interest in the aviation industry?",
        ],
    },
    deloitte: {
        label: "Deloitte",
        icon: "🟢",
        domain: "deloitte.com",
        color: "#86BC25",
        list: [
            "How do you approach a complex business problem for a new client?",
            "Explain your experience with digital strategy and technology implementation.",
            "How do you manage client expectations and project timelines?",
            "What is your approach to conducting a comprehensive technology audit?",
            "Describe a time you led a team through a difficult transformation project.",
            "How do you communicate complex technical findings to non-technical executives?",
            "Why Deloitte, and how do you align with its 'Impact that Matters' mission?",
        ],
    },
    ey: {
        label: "EY",
        icon: "🟡",
        domain: "ey.com",
        color: "#FFE600",
        list: [
            "How do you use data analytics to drive business insights for clients?",
            "Explain your approach to risk management in large-scale IT projects.",
            "How do you ensure regulatory compliance in financial technology solutions?",
            "What is your experience with cloud-based business transformation?",
            "Describe a time you identified a major inefficiency in a client's process.",
            "How do you build trust and long-term relationships with clients?",
            "Why EY, and what is your take on 'Building a Better Working World'?",
        ],
    },
    pwc: {
        label: "PwC",
        icon: "🟠",
        domain: "pwc.com",
        color: "#D04A02",
        list: [
            "How do you approach building a technology roadmap for a client?",
            "Explain your experience with digital trust and cybersecurity consulting.",
            "How do you stay ahead of emerging technology trends to advise clients?",
            "Describe a time you solved a complex problem using a multidisciplinary team.",
            "What is your approach to change management in a digital-first world?",
            "How do you measure the value of a technology investment for a client?",
            "Why PwC, and what excites you about the 'New Equation' strategy?",
        ],
    },
    zepto: {
        label: "Zepto",
        icon: "⚡",
        domain: "zepto.com",
        color: "#830154",
        list: [
            "How would you design a delivery system that guarantees 10-minute delivery?",
            "Explain your strategy for optimizing dark store inventory in real-time.",
            "How do you handle micro-logistics and route optimization for dense urban areas?",
            "What is your approach to predicting demand at a hyper-local level?",
            "How do you ensure low latency for a quick commerce mobile app?",
            "How would you design a real-time tracking system for thousands of delivery partners?",
            "Why Zepto, and what are your thoughts on the future of quick commerce?",
        ],
    },
    blinkit: {
        label: "Blinkit",
        icon: "🟡",
        domain: "blinkit.com",
        color: "#FFD400",
        list: [
            "How would you design a high-frequency supply chain for fresh produce?",
            "Explain how you would handle real-time inventory sync across hundreds of dark stores.",
            "What is your approach to optimizing picker efficiency inside a warehouse?",
            "How do you manage last-mile delivery challenges in Tier-1 cities?",
            "How would you implement a dynamic replacement/refund system for out-of-stock items?",
            "What metrics are most critical for a 10-minute grocery delivery model?",
            "Why Blinkit, and how would you contribute to its operational excellence?",
        ],
    },
    bigbasket: {
        label: "BigBasket",
        icon: "🧺",
        domain: "bigbasket.com",
        color: "#84C225",
        list: [
            "How would you design a cold-chain logistics system for perishable goods?",
            "Explain your approach to managing a large-scale slot-based delivery system.",
            "How do you optimize warehouse operations for thousands of SKUs?",
            "What is your strategy for reducing wastage and improving inventory turnover?",
            "How do you handle complex subscription models for daily essentials like milk?",
            "How would you design a recommendation engine for grocery baskets?",
            "Why BigBasket, and how do you see the evolution from slot-delivery to quick commerce?",
        ],
    },
};